### ISSUE TITLE
How to use TCPPrinter class

### ISSUE THREAD

**Issue by Noah2345** [cod3monk/zpl#13]
Hello, 

we cannot get the TCPPrinter class to work.
Could you please show us an example on how to initiliaze it.
We always get an error with args.utc in the initialization,
Whats should we input for args, if we should input anything?
`printerTcp = zpl.TCPPrinter(host="127.0.0.1")`

Thank you!

**Comment by cod3monk** [comment]
You found a problem which was introduced a couple days ago with #12. I will replace the `args` parameter and replace the logging facilities with the `logging` module. Unfortunately, I don't have a printer available to fully test this, but you can test the pull request once I put it together.
@netliteIT maybe you could test this as well?

**Comment by cod3monk** [comment]
I committed it right into the master branch, because the previous code was genuinely broken.
@Noah2345 can you confirm it is working for you? If so I will make a new release.
@netliteIT we can work on the logging infrastructure, if you have other needs - which are not covered with the changes in e11667571a7c0bb0d689954e4e42af9ded8a4abb

**Comment by Noah2345** [comment]
@cod3monk the TCPPrinter class is now working. Thank you!

**Comment by cod3monk** [comment]
I released version 0.1.4 with this fix
